name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Builds and deploys app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.0]
        os: [ubuntu-latest]

    steps:
    - name: Deploy to Now
      run:
        yarn deploy --token ${{ secrets.NOW_TOKEN }}
