name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Builds and deploys app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.0]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install and build and test
      run: |
        npm install
        npm run build --if-present
#     - name: Lint
#       run: npm lint
    - name: Test
      run: npm test
    - name: Deploy to Now
      uses: actions/zeit-now@1.0.0
      env:
        ZEIT_TOKEN: ${{ secrets.NOW_TOKEN }}
