name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Runs tests and lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.0]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Install + Build
      run: |
        yarn install
        yarn run build --if-present
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
