name: Test

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Builds and deploys app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.0]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: yarn install and build and test
      run: |
        yarn install
        yarn run build --if-present
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
    - name: Deploy to Now
      run:
        yarn deploy --token ${{ secrets.NOW_TOKEN }}
